### ISSUE TITLE
registry not working

### ISSUE THREAD

**Issue by fabiocruzcoelho** [nemonik/sameersbn-gitlab-helm#5]
hello, I'm trying to climb the registry, in your chart, pro to even doesn't work with the following settings.

```
 env:
  signupEnabled: 'false'

  host: '{{ .Values.hostname }}.{{ .Values.domain }}'

  registry:
    enabled: 'true'
    host: 'registry.{{ .Values.hostname }}.{{ .Values.domain }}'
    port: '443'
    apiUrl: 'http://localhost:5000'
```
 the same returns 404, I verified that a service is not created on the k8s with port 5000, which may be the cause of the problem.

Could you help me, or am I doing some wrong configuration?
